### ISSUE TITLE
Additional meta-testing for the Workers Vitest integration

### ISSUE THREAD

**Issue by mrbbot** [cloudflare/workers-sdk#5392]
Currently, the Vitest integration is tested against a suite of example tests. There are some things that can't be tested this way though:

- [x] (Inline) snapshots, updating existing and remove obsolete
- [x] `console.log()`ing (including inside `SELF`) with source maps
- [x] Watch mode (for unit tests and `SELF` integration tests https://github.com/cloudflare/workers-sdk/issues/5384)
- [x] Config validation and pretty-formatting of validation errors
- [x] Concurrent tests failing with isolated storage enabled
- [x] Ensuring required compatibility flags set
- [x] Service worker `main` detection and failure
- [ ] Dynamic `import()` (for unit tests and `SELF` integration tests https://github.com/cloudflare/workers-sdk/issues/5387)
- [x] Large modules chunking

These require us to (re)start Vitest programatically and assert on its output, or interact with a running session. We'll also want to make sure we're testing...

- [x] Fake timers
- [x] Different isolation models
- [x] Mock fallthrough to the internet

**Comment by petebacondarwin** [comment]
Closed by #5869
